// Test generated by RoostGPT for test dm-example-3 using AI Model gpt

package com.in28minutes.fullstack.springboot.jwt.basic.authentication.springbootjwtauthloginlogout.course;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import java.util.Arrays;
import java.util.List;

@Service
public class CoursesHardcodedService_findAll03c0701061Test {

    @InjectMocks
    CoursesHardcodedService service;

    @Mock
    List<Course> mockCourses;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testFindAllCourses() {
        Course course1 = new Course(1, "Course 1", "Description 1");
        Course course2 = new Course(2, "Course 2", "Description 2");
        when(mockCourses.findAll()).thenReturn(Arrays.asList(course1, course2));

        List<Course> courses = service.findAll();
        assertEquals(2, courses.size());
        assertEquals(course1, courses.get(0));
        assertEquals(course2, courses.get(1));
    }

    @Test
    public void testFindAllCoursesEmpty() {
        when(mockCourses.findAll()).thenReturn(new ArrayList<>());

        List<Course> courses = service.findAll();
        assertEquals(0, courses.size());
    }
}