// Test generated by RoostGPT for test dm-example-3 using AI Model gpt

package com.in28minutes.fullstack.springboot.jwt.basic.authentication.springbootjwtauthloginlogout.jwt;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.security.oauth2.jwt.JwtEncoder;

public class JwtTokenService_JwtTokenService5002c3c7dbTest {

    private JwtEncoder jwtEncoder;
    private JwtTokenService jwtTokenService;

    @BeforeEach
    public void setup() {
        jwtEncoder = mock(JwtEncoder.class);
        jwtTokenService = new JwtTokenService(jwtEncoder);
    }

    @Test
    public void testJwtTokenServiceConstructor() {
        // Mocking JwtEncoder
        JwtEncoder jwtEncoderMock = mock(JwtEncoder.class);
        
        // Creating JwtTokenService instance with mocked JwtEncoder
        JwtTokenService jwtTokenService = new JwtTokenService(jwtEncoderMock);

        // Verifying that JwtTokenService instance is created successfully
        assertEquals(jwtEncoderMock, jwtTokenService.getJwtEncoder());
    }

    @Test
    public void testJwtTokenServiceConstructorWithNullJwtEncoder() {
        // Creating JwtTokenService instance with null JwtEncoder
        JwtTokenService jwtTokenService = new JwtTokenService(null);

        // Verifying that JwtTokenService instance is created with null JwtEncoder
        assertEquals(null, jwtTokenService.getJwtEncoder());
    }
}