// Test generated by RoostGPT for test dm-example-3 using AI Model gpt

package com.in28minutes.fullstack.springboot.jwt.basic.authentication.springbootjwtauthloginlogout.jwt;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class JwtTokenResponse_JwtTokenResponsee4a2dce87aTest {

    private JwtTokenResponse jwtTokenResponse;

    @BeforeEach
    public void setUp() {
        jwtTokenResponse = new JwtTokenResponse("sampleToken");
    }

    @Test
    public void testJwtTokenResponse() {
        String expectedToken = "sampleToken";
        assertEquals(expectedToken, jwtTokenResponse.token(), "Token does not match the expected value");
    }

    @Test
    public void testJwtTokenResponseWithEmptyToken() {
        JwtTokenResponse jwtTokenResponseEmpty = new JwtTokenResponse("");
        String expectedToken = "";
        assertEquals(expectedToken, jwtTokenResponseEmpty.token(), "Token does not match the expected value");
    }

}