// Test generated by RoostGPT for test dm-java-example1 using AI Model gpt

package com.in28minutes.springboot.rest.example.student;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class Student_setPassportNumber8bba5b77d0Test {

    @Mock
    private Student student;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        student = new Student();
    }

    @Test
    public void testSetPassportNumber() {
        String passportNumber = "123456789";
        student.setPassportNumber(passportNumber);
        assertEquals(passportNumber, student.getPassportNumber());
    }

    @Test
    public void testSetPassportNumberWithNull() {
        assertThrows(NullPointerException.class, () -> {
            student.setPassportNumber(null);
        });
    }

    @Test
    public void testSetPassportNumberWithEmptyString() {
        String passportNumber = "";
        student.setPassportNumber(passportNumber);
        assertEquals(passportNumber, student.getPassportNumber());
    }
}