// Test generated by RoostGPT for test dm-java-example1 using AI Model gpt

package com.in28minutes.springboot.rest.example.student;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import java.net.URI;
import java.net.URISyntaxException;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.http.ResponseEntity;

import com.in28minutes.springboot.rest.example.student.Student;
import com.in28minutes.springboot.rest.example.student.StudentRepository;
import com.in28minutes.springboot.rest.example.student.StudentResource;

public class StudentResource_createStudent5578ece09eTest {

    @InjectMocks
    StudentResource studentResource;

    @Mock
    StudentRepository studentRepository;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testCreateStudent_success() throws URISyntaxException {
        Student student = new Student();
        student.setId(1L);
        student.setName("John");
        student.setPassportNumber("E1234567");

        when(studentRepository.save(student)).thenReturn(student);

        ResponseEntity<Object> responseEntity = studentResource.createStudent(student);

        assertEquals(201, responseEntity.getStatusCodeValue());
        assertEquals(new URI("/1"), responseEntity.getHeaders().getLocation());
    }

    @Test
    public void testCreateStudent_failure() {
        Student student = new Student();

        when(studentRepository.save(student)).thenReturn(null);

        ResponseEntity<Object> responseEntity = studentResource.createStudent(student);

        assertEquals(500, responseEntity.getStatusCodeValue());
    }
}