// Test generated by RoostGPT for test dm-java-example1 using AI Model gpt

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.when;

@SpringBootTest
@ExtendWith(MockitoExtension.class)
public class StudentResource_retrieveStudent9c2c90d0abTest {

    @InjectMocks
    private StudentResource studentResource;

    @Mock
    private StudentRepository studentRepository;

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
        student.setId(1L);
        student.setName("John");
        student.setDescription("Description");
    }

    @Test
    public void testRetrieveStudent_success() {
        when(studentRepository.findById(1L)).thenReturn(Optional.of(student));
        Student result = studentResource.retrieveStudent(1L);
        assertEquals(student, result);
    }

    @Test
    public void testRetrieveStudent_studentNotFound() {
        when(studentRepository.findById(1L)).thenReturn(Optional.empty());
        assertThrows(StudentNotFoundException.class, () -> studentResource.retrieveStudent(1L));
    }
}