// Test generated by RoostGPT for test dm-java-example1 using AI Model gpt

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

public class StudentNotFoundException_StudentNotFoundExceptionddad8dc0e6Test {

    @Test
    public void testStudentNotFoundException() {
        String exceptionMessage = "Student not found exception";
        try {
            throw new StudentNotFoundException(exceptionMessage);
        } catch (StudentNotFoundException ex) {
            Assertions.assertEquals(exceptionMessage, ex.getMessage());
        }
    }

    @Test
    public void testStudentNotFoundExceptionWithEmptyMessage() {
        String exceptionMessage = "";
        try {
            throw new StudentNotFoundException(exceptionMessage);
        } catch (StudentNotFoundException ex) {
            Assertions.assertEquals(exceptionMessage, ex.getMessage());
        }
    }
}