// Test generated by RoostGPT for test dm-java-example1 using AI Model gpt

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Student_setIde5ec36044aTest {

    private Student student;

    @BeforeEach
    public void setup() {
        student = new Student();
    }

    @Test
    public void testSetId() {
        Long id = 100L;
        student.setId(id);
        assertEquals(id, student.getId(), "The ID set in the student object should match the ID retrieved from the student object");
    }

    @Test
    public void testSetId_Null() {
        Long id = null;
        student.setId(id);
        assertEquals(id, student.getId(), "The ID set in the student object should match the ID retrieved from the student object");
    }
}
