// Test generated by RoostGPT for test dm-java-example1 using AI Model gpt

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.MockitoAnnotations;

public class Student_Student79727d4203Test {

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testStudentConstructor() {
        Student student = new Student(1L, "John Doe", "AB123456");
        Assertions.assertEquals(1L, student.getId());
        Assertions.assertEquals("John Doe", student.getName());
        Assertions.assertEquals("AB123456", student.getPassportNumber());
    }

    @Test
    public void testStudentConstructorWithNullValues() {
        Student student = new Student(null, null, null);
        Assertions.assertNull(student.getId());
        Assertions.assertNull(student.getName());
        Assertions.assertNull(student.getPassportNumber());
    }
}