// Test generated by RoostGPT for test dm-java-example1 using AI Model gpt

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_setNamea0b4b9622dTest {

    private Student student;

    @BeforeEach
    public void setup() {
        student = new Student();
    }

    @Test
    public void testSetName() {
        String expectedName = "John Doe";
        student.setName(expectedName);
        assertEquals(expectedName, student.getName(), "The name of the student should be set correctly.");
    }

    @Test
    public void testSetName_Null() {
        String expectedName = null;
        student.setName(expectedName);
        assertEquals(expectedName, student.getName(), "The name of the student should be null.");
    }
}
