// Test generated by RoostGPT for test dm-java-example1 using AI Model gpt

package com.in28minutes.springboot.rest.example.student;

import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.doNothing;
import static org.mockito.ArgumentMatchers.anyLong;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.boot.test.context.SpringBootTest;
import com.in28minutes.springboot.rest.example.student.StudentRepository;

@SpringBootTest
public class StudentResource_deleteStudent4580da98e2Test {

    @InjectMocks
    private StudentResource studentResource;

    @Mock
    private StudentRepository studentRepository;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testDeleteStudent_validId() {
        // Given
        long id = 1L;
        doNothing().when(studentRepository).deleteById(anyLong());

        // When
        studentResource.deleteStudent(id);

        // Then
        verify(studentRepository, times(1)).deleteById(id);
    }

    @Test
    public void testDeleteStudent_invalidId() {
        // Given
        long id = -1L;
        doNothing().when(studentRepository).deleteById(anyLong());

        // When
        studentResource.deleteStudent(id);

        // Then
        verify(studentRepository, times(1)).deleteById(id);
    }
}