// Test generated by RoostGPT for test dm-java-example1 using AI Model gpt

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@SpringBootTest
public class Student_getPassportNumberaa3bc55c5bTest {

    @InjectMocks
    private Student student;

    @Mock
    private Passport passport;

    @Test
    public void testGetPassportNumber_WhenPassportNumberIsNotNull() {
        String expectedPassportNumber = "AB123456";
        when(passport.getNumber()).thenReturn(expectedPassportNumber);
        student.setPassport(passport);
        String actualPassportNumber = student.getPassportNumber();
        assertEquals(expectedPassportNumber, actualPassportNumber, "The passport numbers should match");
    }

    @Test
    public void testGetPassportNumber_WhenPassportNumberIsNull() {
        when(passport.getNumber()).thenReturn(null);
        student.setPassport(passport);
        String actualPassportNumber = student.getPassportNumber();
        assertEquals(null, actualPassportNumber, "The passport number should be null");
    }
}