// Test generated by RoostGPT for test dm-java-example1 using AI Model gpt

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Assertions;
import static org.mockito.Mockito.*;

public class Student_getNamee79d2c9ab8Test {

    private Student student;

    @BeforeEach
    public void setup() {
        student = mock(Student.class);
    }

    @Test
    public void testNameGetterWhenNameIsSet() {
        // Arrange
        when(student.getName()).thenReturn("John Doe");

        // Act
        String name = student.getName();

        // Assert
        Assertions.assertEquals("John Doe", name);
    }

    @Test
    public void testNameGetterWhenNameIsNotSet() {
        // Arrange
        when(student.getName()).thenReturn(null);

        // Act
        String name = student.getName();

        // Assert
        Assertions.assertNull(name);
    }
}
