// Test generated by RoostGPT for test dm-java-example1 using AI Model gpt

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_getPassportNumberaa3bc55c5bTest {

    @InjectMocks
    private Student student;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetPassportNumberWhenPassportNumberIsSet() {
        String expectedPassportNumber = "AB123456";
        student.setPassportNumber(expectedPassportNumber);
        String actualPassportNumber = student.getPassportNumber();
        assertEquals(expectedPassportNumber, actualPassportNumber, "Passport number should match the set value");
    }

    @Test
    public void testGetPassportNumberWhenPassportNumberIsNotSet() {
        String actualPassportNumber = student.getPassportNumber();
        assertEquals(null, actualPassportNumber, "Passport number should be null when not set");
    }
}
