// Test generated by RoostGPT for test dm-java-example1 using AI Model gpt

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_setPassportNumber8bba5b77d0Test {

    @Mock
    private Student student;

    @BeforeEach
    public void init() {
        MockitoAnnotations.openMocks(this);
        student = new Student();
    }

    @Test
    public void testSetPassportNumber_ValidNumber() {
        String validPassportNumber = "123456789";
        student.setPassportNumber(validPassportNumber);
        assertEquals(validPassportNumber, student.getPassportNumber(), "Passport number should be set correctly");
    }

    @Test
    public void testSetPassportNumber_NullNumber() {
        String nullPassportNumber = null;
        student.setPassportNumber(nullPassportNumber);
        assertEquals(nullPassportNumber, student.getPassportNumber(), "Passport number should be set to null");
    }
}
