// Test generated by RoostGPT for test dm-java-example1 using AI Model gpt

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Student_Studentb2349b4fdbTest {

    @Test
    public void testStudentConstructor() {
        try {
            Student student = new Student();
        } catch (Exception e) {
            fail("Creation of Student object failed with exception: " + e.getMessage());
        }
    }
}
