// Test generated by RoostGPT for test dm-java-example1 using AI Model gpt

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import com.in28minutes.springboot.rest.example.student.repository.StudentRepository;

import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.anyLong;

public class StudentResource_deleteStudent4580da98e2Test {

    @InjectMocks
    StudentResource studentResource;

    @Mock
    StudentRepository studentRepository;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testDeleteStudent() {
        studentResource.deleteStudent(1L);
        verify(studentRepository, times(1)).deleteById(anyLong());
    }

    @Test
    public void testDeleteStudent_NegativeId() {
        studentResource.deleteStudent(-1L);
        verify(studentRepository, times(0)).deleteById(anyLong());
    }
}