// Test generated by RoostGPT for test dm-java-example1 using AI Model gpt

package com.in28minutes.springboot.rest.example.student;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Student_Student79727d4203Test {

    private Student student;

    @BeforeEach
    public void setUp() {
        student = new Student();
    }

    @Test
    public void testStudentId() {
        Long id = 1L;
        String name = "John Doe";
        String passportNumber = "A1234567";

        student = new Student(id, name, passportNumber);

        assertEquals(id, student.getId(), "The id should match the constructor argument");
    }

    @Test
    public void testStudentName() {
        Long id = 1L;
        String name = "John Doe";
        String passportNumber = "A1234567";

        student = new Student(id, name, passportNumber);

        assertEquals(name, student.getName(), "The name should match the constructor argument");
    }

    @Test
    public void testStudentPassportNumber() {
        Long id = 1L;
        String name = "John Doe";
        String passportNumber = "A1234567";

        student = new Student(id, name, passportNumber);

        assertEquals(passportNumber, student.getPassportNumber(), "The passport number should match the constructor argument");
    }

    @Test
    public void testStudentWithNullValues() {
        Long id = null;
        String name = null;
        String passportNumber = null;

        student = new Student(id, name, passportNumber);

        assertEquals(id, student.getId(), "The id should be null");
        assertEquals(name, student.getName(), "The name should be null");
        assertEquals(passportNumber, student.getPassportNumber(), "The passport number should be null");
    }
}
