// Test generated by RoostGPT for test dm-java-example1 using AI Model gpt

```java
package com.in28minutes.springboot.rest.example.student;

import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.http.ResponseEntity;
import com.in28minutes.springboot.rest.example.student.Student;
import com.in28minutes.springboot.rest.example.student.StudentRepository;
import com.in28minutes.springboot.rest.example.student.StudentResource;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class StudentResource_updateStudent3007a464c6Test {

    @InjectMocks
    StudentResource studentResource;

    @Mock
    StudentRepository studentRepository;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testUpdateStudentSuccess() {
        Student student = new Student("John", "Doe");
        when(studentRepository.findById(1L)).thenReturn(Optional.of(student));
        ResponseEntity<Object> response = studentResource.updateStudent(student, 1L);
        assertEquals(204, response.getStatusCodeValue());
    }

    @Test
    public void testUpdateStudentNotFound() {
        Student student = new Student("John", "Doe");
        when(studentRepository.findById(1L)).thenReturn(Optional.empty());
        ResponseEntity<Object> response = studentResource.updateStudent(student, 1L);
        assertEquals(404, response.getStatusCodeValue());
    }
}