// Test generated by RoostGPT for test dm-java-example1 using AI Model gpt

package com.in28minutes.springboot.rest.example.student;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import com.in28minutes.springboot.rest.example.student.Student;
import com.in28minutes.springboot.rest.example.student.StudentRepository;

public class StudentResource_retrieveAllStudents20c77fb2dcTest {

    @InjectMocks
    private StudentResource studentResource;

    @Mock
    private StudentRepository studentRepository;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testRetrieveAllStudents() {
        Student student1 = new Student(1, "John", "A");
        Student student2 = new Student(2, "Jane", "B");
        List<Student> students = Arrays.asList(student1, student2);
        
        when(studentRepository.findAll()).thenReturn(students);
        
        List<Student> result = studentResource.retrieveAllStudents();
        
        assertEquals(2, result.size());
        assertEquals(student1, result.get(0));
        assertEquals(student2, result.get(1));
    }

    @Test
    public void testRetrieveAllStudents_empty() {
        when(studentRepository.findAll()).thenReturn(Arrays.asList());
        
        List<Student> result = studentResource.retrieveAllStudents();
        
        assertEquals(0, result.size());
    }
}